hello-world:
  stage: build
  artifacts:
    reports:
      dotenv: build.env
  script:
    - echo 'IMAGE=busybox:latest' > build.env

hello-world-2:
  stage: build
  needs: ["hello-world"]
  image: $IMAGE
  script:
    - echo hello world