workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        IS_TAG_BUILD: 1
    - if: $CI_COMMIT_TAG == null
      variables:
        IS_TAG_BUILD: 0

hello-world:
  stage: build
  script:
    - echo IS_TAG_BUILD - $IS_TAG_BUILD
