name: CI/CD
on: [push]
env:
  DOCKER_BUILDKIT: 1
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir build
      - run: cd build
      - run: "echo 'FROM nginx' > Dockerfile"
      - run: echo docker build -t ${{ github.repository }}:latest .
      - run: docker build -t ${{ github.repository }}:latest .
