name: CI/CD
on: [push]
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      # add node
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm install -g gitlab-ci-local
      - run: gitlab-ci-local
